name: kevents
description: Event Management App for Kurukshetra CEG.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1
  csv: ^5.1.1
  lottie: ^3.0.0
  file_picker: ^6.1.1
  dart_jsonwebtoken: ^2.12.1
  filesystem_picker: ^4.0.0
  shared_preferences: ^2.2.2
  pem: ^2.0.4
  rive: ^0.12.0
  google_fonts: ^6.1.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.1
  dio: ^5.4.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.6.0
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.2
  glassmorphism_ui: ^0.3.0
  animated_snack_bar: ^0.4.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/public.pem
    - assets/RiveAssets/

  fonts:
    - family: NovaSquare
      fonts:
        - asset: assets/fonts/NovaSquare-Regular.ttf
    - family: MeteoricLight
      fonts:
        - asset: assets/fonts/Meteoric-light.otf
    - family: Anxiety
      fonts:
        - asset: assets/fonts/anxiety-anxiety-regular-400.otf
    - family: Nasalization
      fonts:
        - asset: assets/fonts/nasalization-rg.otf
    - family: ProductSans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
